"use client"
import Link from 'next/link';
import { usePathname, useRouter } from 'next/navigation';
import React from 'react';
export const metadata = {
    title: "Navbar",
    description: "Generated by create nav links",
  };
const NavbarPage = () => {
    const pathName = usePathname()
    const routes = useRouter()
    const links = [
        {
            title: "Meals",
            path: "/meals"
        },
        {
            title: "About",
            path: "/about"
        },
        {
            title: "Bolgs",
            path: "/bolgs"
        },
        {
            title: "Posts",
            path: "/posts"
        },
        {
            title: "Contacts",
            path: "/contacts"
        },
        {
            title: "TestPost",
            path: "/testPosts"
        },
        {
            title: "Gallery",
            path: "/gallery"
        },
        {
            title: "Dashboard",
            path: "/dashboard"
        },
    ]
    const handler = ()=>{
        routes.push('/login')
    }
    if(pathName.includes("dashborad"))
        return <div className='bg-green-500'></div>

    return (
        <div>
            <nav className='flex text-white/90 bg-teal-500 py-2 items-center justify-between'>
                <h6 className='text-2xl font-semibold'>Next Projects</h6>
                <ul className='space-x-4'>
                    {
                        links.map((link) => <Link className={`${pathName === link.path && "text-orange-500 underline underline-offset-8"}`} key={link.path} href={link.path}>{link.title}</Link>)
                    }
                </ul>
                <button onClick={handler} className='border-2 py-1 px-3 rounded'>Login</button>
            </nav>
        </div>
    );
};

export default NavbarPage;